/**
 * Graphify integration module.
 *
 * This module provides utilities for running the Graphify CLI and parsing its output.
 * Graphify extracts knowledge graph structure from code files (AST-based analysis)
 * and generates graph.json with nodes and edges representing concepts and relationships.
 */

import { execSync } from "child_process";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

/**
 * Graphify node structure as generated by the CLI.
 */
export interface GraphifyNode {
  id: string;
  label: string;
  type: string;
  filePath?: string;
  connections?: number;
}

/**
 * Graphify edge structure as generated by the CLI.
 */
export interface GraphifyEdge {
  source: string;
  target: string;
  label?: string;
}

/**
 * Complete graph structure from Graphify output.
 */
export interface GraphifyGraph {
  nodes: GraphifyNode[];
  edges: GraphifyEdge[];
}

/**
 * Executes the Graphify CLI to extract knowledge graph from the project.
 *
 * @param projectRoot - Absolute path to the project root directory
 * @throws Error if Graphify execution fails or times out
 */
export function runGraphify(projectRoot: string): void {
  try {
    // Run Graphify with a 60-second timeout
    // The command updates the graph based on current codebase
    execSync("graphify update .", {
      cwd: projectRoot,
      timeout: 60000,
      stdio: "pipe",
    });
  } catch (error) {
    console.error("Graphify execution failed:", error);
    throw new Error("Graphify extraction failed");
  }
}

/**
 * Reads and parses the Graphify-generated graph.json file.
 *
 * @param projectRoot - Absolute path to the project root directory
 * @returns Parsed graph data or null if file doesn't exist or is invalid
 */
export function readGraphifyOutput(projectRoot: string): GraphifyGraph | null {
  const graphPath = join(projectRoot, "graphify-out", "graph.json");

  if (!existsSync(graphPath)) {
    return null;
  }

  try {
    const raw = readFileSync(graphPath, "utf-8");
    return JSON.parse(raw) as GraphifyGraph;
  } catch (error) {
    console.error("Failed to parse Graphify output:", error);
    return null;
  }
}
